### ISSUE TITLE
Debugging with Eclipse and PyDev v7.3.0

### ISSUE THREAD

**Issue by carjohnson** [SlicerRt/SlicerDebuggingTools#10]
I have been using Eclipse to debug my Python code with PyDev v7.0.3
When I updated the PyDev module to version 7.3.0 through the Eclipse IDE, Slicer was no longer able to connect. The following error message appeared in the Python Interactor 

_Traceback (most recent call last):
  File "C:/Users/cjohnson/AppData/Roaming/NA-MIC/Extensions-28438/DebuggingTools/lib/Slicer-4.11/qt-scripted-modules/PyDevRemoteDebug.py", line 158, in setup
    if self.logic.isConnected():
  File "C:/Users/cjohnson/AppData/Roaming/NA-MIC/Extensions-28438/DebuggingTools/lib/Slicer-4.11/qt-scripted-modules/PyDevRemoteDebug.py", line 575, in isConnected
    return pydevd.connected
AttributeError: module 'pydevd' has no attribute 'connected'_

Comparing the pydevd.py scripts for both versions shows that in 7.3.0 there is no longer a global variable 'connected'. 
This error leaves the Slicer Debugger module in a strange state - not allowing me to change the location of the pydevd.py file back to the older version. I had to manually change this in the Slicer.ini file.

I am using Slicer version 4.11.0-2019-08-13

**Comment by lassoan** [comment]
Could you please try if it works if you catch the AttributeError exception and return False?

Is there any replacement for `connected` attribute in pydevd 7.3.0?

**Comment by carjohnson** [comment]
This error doesn't happen in my code - so there is no opportunity to catch the error on my end.
This occurs when you try to open the Python debugger module.
I have attached a picture of what seems to be a relevant section of a file comparison of pydevd.py for both versions using WinMerge. It looks like they may have changed the attribute from connected to _debugger_setup . 

![SlicerPythonDebugError](https://user-images.githubusercontent.com/4127051/63695322-6ad10700-c7e6-11e9-8435-f9d4b995c236.png)

**Comment by lassoan** [comment]
Fixed by https://github.com/SlicerRt/SlicerDebuggingTools/commit/0506ece240568cbd2f4adfa680be3f277e25864f
