### ISSUE TITLE
PyCharm debug connection issue - attach_amd64.dll

### ISSUE THREAD

**Issue by kleingeo** [SlicerRt/SlicerDebuggingTools#12]
When trying to connect PyCharm (version 2020.3.5) to Slicer (version 4.11.0-2020-09-22) I am constantly getting an error saying 

```python
Expected: /PyCharm 2019.3.3\debug-eggs\pydevd-pycharm.egg\pydevd_attach_to_process\attach_amd64.dll to exist.
```

but I am not sure how to fix this.

**Comment by lassoan** [comment]
There is nothing to fix, this is a false alarm in PyCharm. There is nothing to do on our side, you can safely ignore the message.

Unfortunately, PyCharm developers very often introduce smaller or larger bugs in their debugger. It seems that the debugger does not represented will in their quality assurance process.
