### ISSUE TITLE
Problems with Pycharm 2024.3 - Does not connect

### ISSUE THREAD

**Issue by nkoser** [SlicerRt/SlicerDebuggingTools#19]
Hi, 

with the current Pycharm version 2024.3 debugging is not possible, because it does not even wait for a connection, but still listens on the port. If you then open Slicer and want to connect, it cannot connect to the debugging server. I have tested this for Mac and Windows. My solution was to set Pycharm to an older version (2023.3.7) so that it worked again. 

Best Regards
Niklas

**Comment by lassoan** [comment]
Unfortunately, PyCharm developers often break their debugger. This happened again in 2024.3:

https://youtrack.jetbrains.com/issue/PY-77357/Python-Debug-Server-with-pydevd-pycharm-stopped-working-in-2024.3

They provided a workaround:

> Disable python.debug.use.single.port in Help | Find Action | Registry.
