### ISSUE TITLE
No error message if import ptvsd failed

### ISSUE THREAD

**Issue by mmoslehy** [SlicerRt/SlicerDebuggingTools#5]
When the button is clicked, the window pops up as if everything is normal, then it disappears
When the window pops up, and there is an error it is reported in the Python console in red.
However, I am afraid when users don't have the Python console shown, they have no idea what is going on.
![output_wnpwg5](https://user-images.githubusercontent.com/22180044/28326483-e5ab8554-6bae-11e7-8bc1-2b6251007b91.gif)

**Comment by lassoan** [comment]
Thanks for reporting. I've added missing files to the package. Please test it in tomorrow's nightly build and reopen the issue if it still exist.
