### ISSUE TITLE
Error when trying to auto-connect using qt5

### ISSUE THREAD

**Issue by Kmacneil0102** [SlicerRt/SlicerDebuggingTools#7]
Using the Windows nightly that had qt5 (from 01/19).
When checking the "Auto-connect on next application startup" checkbox, an error is sometimes thrown, as seen below: 
![image](https://user-images.githubusercontent.com/22458394/35396698-67e844a6-01bb-11e8-8cfc-b9bccf015450.png)

This seems to stem from what is returned from `QSettings.value() ` when the value set is a boolean. From what I can tell from my bit of testing, this happens regardless of if the value is either `True` or `False`, sometimes returning `u'true'` or `u'false'` or the boolean equivalents. When boolean is returned is when the error occurs, due to the lack of a `.lower()`.

I've had trouble testing further as it seems it happens when the settings get written to and read from a file rather than just setting a value and reading it from `QSettings()`.

**Comment by lassoan** [comment]
Thanks for reporting this. I see strange things in settings since I use Qt4 and Qt5 based Slicer on the same computer. There might be slight differences in how they store settings. Could you try and add type checks or exception handling to cover all cases that you encounter?

**Comment by Kmacneil0102** [comment]
I just did a bit more testing and I think i've determined the consistent behaviour at least. If you set a value in `QSettings()` that is a boolean, and then read that value again before a restart of Slicer, it will always return the boolean. However, if you restart Slicer first, when you read the value from `QSettings()` it will return a unicode string such as `u'true'`. 

Looking at the Slicer.ini file, the value gets inserted as a lowercase 'true' or 'false', but until the settings are reset/resynced (whatever happens when Slicer is restarted), the value will retain its type it was set as. This also holds true for int (it will read out as int until Slicer is restarted).

**Comment by Kmacneil0102** [comment]
Simple fix is changing this line: 
`settings.setValue('Developer/PythonRemoteDebugAutoConnect', autoConnect)`
to
`settings.setValue('Developer/PythonRemoteDebugAutoConnect', str(autoConnect))`

This will ensure that there is no ambiguity about the type expected, not sure if there is a better solution.

**Comment by lassoan** [comment]
OK, I'll just change that in the code then.

**Comment by lassoan** [comment]
I've committed a fix, went with `'true' if autoConnect else 'false'` because in Slicer.ini Boolean flags are always appear with lowercase. It would be nice if you could test it.

**Comment by Kmacneil0102** [comment]
I replaced the line in my own code and it seems to work as intended now on Slicer versions using both Qt4 and Qt5!
