### ISSUE TITLE
pycharm-debug.egg missing

### ISSUE THREAD

**Issue by sedghi** [SlicerRt/SlicerDebuggingTools#9]
I have a professional PyCharm, and I followed the wiki tutorials but in my debug-eggs folder i only see ``pydevd-pycharm.egg``. I don't see any ``pycharm-debug.egg``

PyCharm 2019.1.3 (Professional Edition)
Build #PY-191.7479.30, built on May 29, 2019
JRE: 11.0.2+9-b159.60 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-54-generic

on Slicer 4.11.0-2019-07-19 r28397

Ubuntu 16.04 LTS 

Any comment is appreciated

**Comment by sedghi** [comment]
Update: Apparently the debugging works with the ``pydevd-pycharm.egg'', so maybe it's good to remove restriction that the name should be ``pycharm-debug.egg``

**Comment by lassoan** [comment]
Thanks for reporting this. PyCharm has changed the debug egg filename recently and we missed doing the necessary changes at a few places. I've now updated the file filter in the manual file selector and the label on the GUI.
